apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dummysites.dummysites.dwk.io
spec:
  group: dummysites.dwk.io
  scope: Namespaced
  names:
    kind: DummySite
    singular: dummysite
    plural: dummysites
    shortNames:
      - ds
      - dsite
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                website_url:
                  type: string
                image:
                  type: string
      additionalPrinterColumns:
        - name: Website
          description: Website to clone
          jsonPath: .spec.website_url
          type: string

        - name: Image
          description: Image used to create
          type: string
          jsonPath: .spec.image
