apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: project-http-rt
spec:
  parentRefs:
    - name: project-gw
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/v1
      backendRefs:
        - name: todo-app-service
          port: 81

    - matches:
        - path:
            type: PathPrefix
            value: /

      backendRefs:
        - name: todo-app-service
          port: 80
