---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - './serviceAccount.yaml'
  - './clusterole.yaml'
  - './clusterrolebinding.yaml'
  - './countdown-controller.yaml'
  - './countdown-crd.yaml'
  - './countdown.yaml'

