---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "config/potsgres.configmap.yaml"
  - "deployment/project.v1.deployment.yaml"
  - "gateway/project.gateway.yaml"
  - "gateway/project.route.yaml"
  - "services/project.v1.service.yaml"
  - "statefulsets/postgres.statefulset.yaml"
  - "storage/pvc.yaml"
