apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pingpong-ing
  labels:
    app.kubernetes.io/name: pingpong-ing
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/pingpong"
            backend:
              service:
                name: pingpong-svc
                port:
                  number: 80
