---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: pingpong-restart-rate

spec:
  metrics:
    - name: pingpong-restart-rate
      initialDelay: 2m
      successCondition: result < 5
      provider:
        prometheus:
          address: http://prometheus-kube-prometheus-stack-prometheus-0.prometheus.svc.cluster.local:9090
          query: |
            scalar(
              sum(
                rate(container_cpu_usage_seconds_total{namespace="default", container!=""}[5m])) * 100
            )
