---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "pingpong.deployment.v1.yaml"
  - "pg.configmap.yaml"
  - "pg.statefulset.yaml"
  - "pingpong.service.yaml"
  - "pingpong.gatway.yaml"
  - "pingpong.route.yaml"
