apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap

data:
  PG_HOST: pg-service
  PG_PASSWORD: foss
  DB_NAME: pingpong
  PG_USER: itsfoss
  init.sql: |
    -- init the database
    \c pingpong;

    CREATE TABLE IF NOT EXISTS pings (
      id SERIAL PRIMARY KEY,
      createdat TIMESTAMP NOT NULL DEFAULT NOW(),
      count INTEGER NOT NULL
    );
