apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "rollout.yaml"
  - "analysistemplate.yaml"
images:
  - name: PROJECT/IMAGE
    newName: mluukkai/dwk-app8
    newTag: v1
