apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dummysite-binding

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dummysite-role

subjects:
  - kind: ServiceAccount
    name: dummysite-serviceaccount
    namespace: default
