apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifest/read-write.deployment.v1.yaml


images:
- name: PROJECT/READER
  newName: akhonya/reader
  newTag: ff1d1b901a7d5b1cf78758647e7837f870202859
- name: PROJECT/WRITTER
  newName: akhonya/writter
  newTag: ff1d1b901a7d5b1cf78758647e7837f870202859
