apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifest/read-write.deployment.v1.yaml


images:
- name: PROJECT/READER
  newName: akhonya/reader
  newTag: v1
- name: PROJECT/WRITTER
  newName: akhonya/writter
  newTag: v1
