apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifest/read-write.deployment.v1.yaml


images:
- name: PROJECT/READER
  newName: akhonya/reader
  newTag: dad3c55d572803e4ad5cb7f22ea9ee5939ab7fbb
- name: PROJECT/WRITTER
  newName: akhonya/writter
  newTag: dad3c55d572803e4ad5cb7f22ea9ee5939ab7fbb
