apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifest/read-write.deployment.v1.yaml


images:
- name: PROJECT/READER
  newName: akhonya/reader
  newTag: cecdde26d7acde7e8942054eea81e695ec25c3c6
- name: PROJECT/WRITTER
  newName: akhonya/writter
  newTag: cecdde26d7acde7e8942054eea81e695ec25c3c6
