---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: nats
    releaseName: my-nats
    repo: oci://registry-1.docker.io/bitnamicharts
    valuesFile: values.yaml
