---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "./serviceaccounts/dummy-controller-sa.yaml"
  - "./operators/dummycontroller.yaml"
  - "./roles/clusterole.yaml"
  - "./roles/clusterolebinding.yaml"
  - "./workloads/example.dummysites.yaml"
  - "./workloads/google.dummysite.yaml"
