name: Release Pingpong Application

on:
  push:
    paths:
      - ".github/workflows/**"
      - "gke/pingpong/**"

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER}}
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: ${{ secrets.REPO_NAME }}
  IMAGE: pingpong
  SERVICE: pingpong-dep

  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    if: github.event.ref_type == 'branch'
    name: build publish and deploy
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Code to Runner"
        uses: actions/checkout@v4

      - name: "Authenticate to Google Cloud"
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v2

      - name: "Use gcloud CLI"
        run: gcloud info

      - name: "Configure Docker to Artifact Registry"
        run: |-
          gcloud auth configure-docker europe-north1-docker.pkg.dev --quiet

      - name: "Get GKE credentials"
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: "${{ env.GKE_CLUSTER }}"
          project_id: "${{ env.PROJECT_ID }}"
          location: "${{ env.GKE_ZONE }}"

      - name: "Compose the Image name"
        run: echo "IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build Container Image
        working-directory: gke/pingpong
        run: docker build --tag $IMAGE_TAG .

      - name: Publish Image
        run: docker push $IMAGE_TAG

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Deploy
        working-directory: gke/pingpong/manifests
        run: |-
          NAMESPACE="${GITHUB_REF#refs/heads/}"
          if [ "$NAMESPACE" = "main" ]; then
            NAMESPACE="project"
          fi

          kubectl create namespace "$NAMESPACE" || true
          kubectl config set-context --current --namespace="$NAMESPACE"
          kustomize edit set namespace "$NAMESPACE"
          kustomize edit set image PROJECT/IMAGE=$IMAGE_TAG
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment $SERVICE
          kubectl get services -o wide
