name: Build and Publish Todoist to Container Registry

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "project/**"

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PAT: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ env.DOCKER_USERNAME}}"
          password: "${{ env.DOCKER_PAT }}"

      - name: Build and Publish 'backend' image
        working-directory: project/backend
        run: |-
          docker build --tag "akhonya/dwk-backend:$GITHUB_SHA" .
          docker push "akhonya/dwk-backend:$GITHUB_SHA"

      - name: Build and Publish 'frontend' image
        working-directory: project/frontend
        run: |-
          docker build --tag "akhonya/dwk-frontend:$GITHUB_SHA" .
          docker push "akhonya/dwk-frontend:$GITHUB_SHA"

      - name: Build and Publish 'broadcaster' image
        working-directory: project/broadcaster
        run: |-
          docker build --tag "akhonya/broadcaster:$GITHUB_SHA" .
          docker push "akhonya/broadcaster:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right image
        working-directory: "project/k8s"
        run: |
          kustomize edit set image PROJECT/BACKEND=akhonya/dwk-backend:$GITHUB_SHA
          kustomize edit set image PROJECT/FRONTEND=akhonya/dwk-frontend:$GITHUB_SHA
          kustomize edit set image PROJECT/BROADCASTER=akhonya/broadcaster:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: "project/k8s/kustomization.yaml"
          message: "[chore]: release new version of application - ${{ github.sha }}"
